# Introduction to NumPy

## Exercises:

### 1. Update/Upgrade the NumPy package to the latest version

In [30]:
pip install numpy --upgrade

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



### 2. Install/Upgrade another package (e.g. Pandas) 

In [31]:
pip install pandas --upgrade

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


### 3. Import NumPy as <i> np </i>

In [32]:
import numpy as np

### 4. Use the<i> np.array() </i>function to create an array variable - <i>array_hw_1</i> with the numbers 4,5,7 and 10 in it

In [33]:
array_hw_1 = np.array([4,5,7,10])

### 5. Display the new array on screen

In [34]:
array_hw_1

array([ 4,  5,  7, 10])

### 6. Create a 2x2 array with the same values as <i> array_hw_2 </i> and display it on the screen

In [35]:
array_hw_2 = np.array([[1,2,3,4],[5,6,7,8]])

In [36]:
array_hw_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 7. Call the <i> np.mean() </i> function on each array

In [37]:
np.mean(array_hw_1)

np.float64(6.5)

In [38]:
np.mean(array_hw_2)

np.float64(4.5)

### 8. Use the <i> axis </i> argument to find the mean for all the rows of <i> array_hw_2</i>

In [39]:
np.mean(array_hw_2,axis=1)

array([2.5, 6.5])

### 9. Use the <i>axis</i> argument to find the mean for all the columns of <i>array_hw_2</i>

In [40]:
np.mean(array_hw_2, axis=0)

array([3., 4., 5., 6.])

### 10. Use the <i> Shift + Tab </i> shorcut on <i> np.mean() </i> to check what possible arguments we can specify. 

### 11. Set the <i> dtype </i> argument equal to <i> np.int </i> and compare the results 

In [ ]:
np.mean(array_hw_2, axis = 0, dtype = np.int)